[versions]
asm_version = "9.8"
commons_io_version = "2.20.0"
fabric_loader_version = "0.17.2+WilderForge.0.2.1"
fontbox_version = "3.0.5"
freetype_version="1.13.1"
gson_version = "2.13.1"
junit_version = "5.13.4"
junit_platform_suite_version = "1.13.4"
log4j_version = "2.24.3"
maven_fetcher_version = "1.1.1+WilderForge.1.0.2"
mixin_version = "0.16.5+mixin.0.8.7"
thrixlvault_version = "0.11.0.1"
workspace_version = "6.5.1.0"

[libraries]
asm = { module = "org.ow2.asm:asm", version.ref = "asm_version" }
asm_analysis = { module = "org.ow2.asm:asm-analysis", version.ref = "asm_version" }
asm_commons = { module = "org.ow2.asm:asm-commons", version.ref = "asm_version" }
asm_tree = { module = "org.ow2.asm:asm-tree", version.ref = "asm_version" }
asm_util = { module = "org.ow2.asm:asm-util", version.ref = "asm_version" }

commons_io = { module = "commons-io:commons-io", version.ref = "commons_io_version" }
fabric-loader = { module = "com.wildermods:fabric-loader", version.ref = "fabric_loader_version" }
fontbox = { module = "org.apache.pdfbox:fontbox", version.ref = "fontbox_version" }
freetype = { module = "com.badlogicgames.gdx:gdx-freetype", version.ref = "freetype_version" }
freetype_platform = { module = "com.badlogicgames.gdx:gdx-freetype-platform", version.ref = "freetype_version" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson_version"}
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit_version" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit_version" }
junit-platform-suite = { module = "org.junit.platform:junit-platform-suite", version.ref = "junit_platform_suite_version" }
log4j = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j_version" }
log4j_api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j_version" }
maven_fetcher = { module = "org.myjtools:maven-fetcher", version.ref = "maven_fetcher_version" }
mixin = { module = "net.fabricmc:sponge-mixin", version.ref = "mixin_version" }
thrixlvault = { module = "com.wildermods:thrixlvault", version.ref = "thrixlvault_version" }
workspace = { module = "com.wildermods.workspace:com.wildermods.workspace.gradle.plugin", version.ref = "workspace_version" }
